version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./test_env/Dockerfile
    volumes:
      - ./:/var/app/
    ports:
      - "8000:8000"
    command: /bin/sh -c "python3 test_env/main.py"

  redis:
    container_name: redis
    image: redis:7.0.2

  db:
    container_name: db
    image: mysql:8.0.29
    volumes:
      - ./test_env/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
